compute_environment: LOCAL_MACHINE
deepspeed_config:
  deepspeed_multinode_launcher: standard
  gradient_accumulation_steps: 1
  offload_optimizer_device: none
  offload_param_device: none
  zero3_init_flag: false
  zero3_save_16bit_model: false
  zero_stage: 2
  gradient_clipping: 0.01
distributed_type: DEEPSPEED 
downcast_bf16: 'yes'
gpu_ids: all
machine_rank: 0
main_process_port: 10000
main_training_function: main
mixed_precision: 'bf16' 
num_machines: 1
num_processes: 4
rdzv_backend: static
same_network: True
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
